#!/bin/bash

outputdir="./output"
mkdir -p $outputdir
inputfilename="${@:$(($#))}"
args="${@:1:$(($#-1))}"
the_command="pdflatex $args -shell-escape -interaction nonstopmode -file-line-error -output-directory=\"$outputdir\" \"$inputfilename\""

echo $the_command
eval $the_command

inotifywait . -q -m -e modify --excludei '^.*\.w18$' --format %f | while read f
do
  echo $f modified
  echo $the_command
  eval $the_command
done
