#!/bin/bash

source ./paths.sh

for i in "${paths[@]}"
do
  mkdir -p $(dirname "$i")
  sudo cp -r "$(realpath $backupdir$i)" "$(dirname $i)"
done

# create directories per ranger bookmarks
ranger_bookmarks="./files$HOME/.config/ranger/bookmarks"
cat "$ranger_bookmarks" | sed 's/^.://' | xargs -L1 mkdir -p
