#!/bin/bash

sudo apt update && sudo apt upgrade

sudo make deploy

sudo apt install \
i3 \
entr \
pcregrep \
ntp \
awscli \
pandoc \
flameshot \
zathura \
latexmk \
texlive \
vlc \
moreutils \
texlive-fonts-extra \
cargo \
yapf \
python-fontforge \
fontforge \
lcdf-typetools  \
dos2unix \
copyq \
blueman \
sxiv \
transmission-gtk \
virtualbox \
unrar \
xdotool \
gimp \
xbacklight \
python3-pip \
chromium-browser \
neovim \
git \
ranger \
zsh \
curl \
silversearcher-ag \
nautilus-dropbox \
jq \
feh \
compton \
rofi \
telegram-desktop \
udiskie \
unclutter \
xclip \
slack \
i3lock-fancy \
neofetch \
fonts-font-awesome \
pianobar \
htop \
translate-shell \
zsh-antigen \
libappindicator1 \
unoconv \
texlive-lang-cyrillic \
inotify-tools \
texlive-generic-recommended \
texlive-latex-extra \
atool

# cargo
curl https://sh.rustup.rs -sSf | sh

sudo cargo install \
  alacritty \
  cargo-deb \
  fd-find \
  ripgrep

# repos
mkdir ~/repos
cd ~/repos

## pip3
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo python3 get-pip.py

## fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

## polybar
sudo apt-get install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2
git clone https://github.com/jaagr/polybar.git && cd mkdir polybar/build && cd polybar/build && cmake .. && sudo make install && cd ..

## htop-vim
git clone https://github.com/KoffeinFlummi/htop-vim && ./autogen.sh && ./configure && sudo make && cd ..

## i3lock-fancy.git
git clone https://github.com/meskarune/i3lock-fancy.git && cd i3lock-fancy && sudo make install && cd ..

## git-quick-stats
git clone https://github.com/arzzen/git-quick-stats.git && cd git-quick-stats && sudo make install && cd ..

## vimiv
git clone https://github.com/karlch/vimiv && cd vimiv && sudo make install && cd ..

## xkb-switch
git clone https://github.com/ierton/xkb-switch && cd xkb-switch && mkdir build && cd build && cmake .. && make && sudo make install && cd ..

## alacritty
# TODO

# brave browser
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add - && echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-`lsb_release -sc`.list && sudo apt update && sudo apt install brave-browser brave-keyring

# pip
sudo pip install jrnl || true
sudo pip2 install pynvim || true
sudo pip3 install pynvim || true
sudo pip3 install khal

i3

gnome-session-quit
