#!/bin/bash

# set keyboard repeat delay
xset r rate 250 32

# set swapiness
sudo sysctl vm.swappiness=1

# create swap file
sudo swapon -s
sudo swapoff /swapfile
sudo fallocate -l 8G /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
sudo swapon -s

# zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

sudo make deploy

mkdir -p ~/Downloads/repos
mkdir -p ~/stuff/images/screenshots
mkdir -p ~/sync
mkdir -p ~/apps
mkdir -p ~/sync/data
mkdir -p ~/sync/devices
mkdir -p ~/stuff/movies
cd ~/Downloads/repos

# mirrors

## nvim
sudo add-apt-repository ppa:neovim-ppa/stable

## i3
/usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
sudo dpkg -i ./keyring.deb
echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | sudo tee -a /etc/apt/sources.list.d/sur5r-i3.list

sudo apt update && sudo apt upgrade

sudo apt install \
    notification-daemon \
    libxkbfile-dev \
    dh-autoreconf \
    gconf2 \
    syncthing \
    libghc-x11-xft-dev \
    autokey-gtk \
    gcalcli \
    conky \
    i3 \
    entr \
    pcregrep \
    ntp \
    awscli \
    pandoc \
    flameshot \
    zathura \
    latexmk \
    texlive \
    vlc \
    moreutils \
    texlive-fonts-extra \
    yapf \
    python-fontforge \
    fontforge \
    lcdf-typetools  \
    dos2unix \
    copyq \
    blueman \
    sxiv \
    transmission-gtk \
    virtualbox \
    unrar \
    xdotool \
    gimp \
    xbacklight \
    python3-pip \
    chromium-browser \
    neovim \
    git \
    ranger \
    zsh \
    curl \
    silversearcher-ag \
    nautilus-dropbox \
    jq \
    feh \
    compton \
    rofi \
    telegram-desktop \
    udiskie \
    unclutter \
    xclip \
    slack \
    i3lock-fancy \
    neofetch \
    fonts-font-awesome \
    pianobar \
    translate-shell \
    zsh-antigen \
    libappindicator1 \
    unoconv \
    texlive-lang-cyrillic \
    inotify-tools \
    texlive-generic-recommended \
    texlive-latex-extra \
    atool

# after installment commands
conky -c ~/.config/conky/conky.conf

# cargo
curl https://sh.rustup.rs -sSf | sh

sudo cargo install \
    cargo-deb \
    fd-find \
    ripgrep

## pip3
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo python3 get-pip.py

## fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

## polybar
sudo apt-get install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2

git clone --branch 3.3 --recursive https://github.com/jaagr/polybar \
    && mkdir -p polybar/build \
    && cd polybar/build \
    && cmake .. \
    && sudo make install \
    && cd ..

## htop-vim
git clone https://github.com/KoffeinFlummi/htop-vim \
    && cd htop-vim \
    && ./autogen.sh \
    && ./configure --disable-unicode \
    && make \
    && sudo make install \
    && cd ..

## i3lock-fancy.git
git clone https://github.com/meskarune/i3lock-fancy.git \
    && cd i3lock-fancy \
    && sudo make install \
    && cd ..

## git-quick-stats
git clone https://github.com/arzzen/git-quick-stats.git \
    && cd git-quick-stats \
    && sudo make install \
    && cd ..

## vimiv
git clone https://github.com/karlch/vimiv \
    && cd vimiv \
    && sudo make install \
    && cd ..

## xkb-switch
git clone https://github.com/ierton/xkb-switch \
    && cd xkb-switch \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && sudo make install \
    && cd ..\

    ## xcwd
git clone https://github.com/schischi/xcwd && cd xcwd && sudo make install && cd ..

## nvm
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

## node
nvm install node

### node packages
sudo npm i -g \
    && prettier \
    && typescript \
    && nodemon

## alacritty
git clone https://github.com/jwilm/alacritty \
    && cd alacritty \
    && cargo build --release \
    && sudo cp target/release/alacritty /usr/local/bin \
    && cd ..

## st
git clone https://github.com/fl0wsnake/st \
    && cd st \
    && sudo make clean \
    && make \
    && sudo make install \
    && cd ..

# ## brave browser
# curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add - && echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ `lsb_release -sc` main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-`lsb_release -sc`.list && sudo apt update && sudo apt install brave-browser brave-keyring

## opera
wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
sudo add-apt-repository "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"
sudo apt install opera-stable

## firefox settings
firefox_dir=$(find ~/.mozilla/firefox/*.default -maxdepth 0 -type d)
mkdir -p $firefox_dir/chrome
echo '#TabsToolbar { visibility: collapse; }' > $firefox_dir/chrome/userChrome.css

## slack
TEMP_DEB="$(mktemp)" \
    && LINK='https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.3-amd64.deb' \
    && wget -O "$TEMP_DEB" $LINK \
    && sudo dpkg -i "$TEMP_DEB" \
    && rm -f "$TEMP_DEB"

## franz
TEMP_DEB="$(mktemp)" \
    && LINK='https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.22/franz_5.0.0-beta.22_amd64.deb' \
    && wget -O "$TEMP_DEB" $LINK \
    && sudo dpkg -i "$TEMP_DEB" \
    && rm -f "$TEMP_DEB"

## postman
cd /tmp || exit
echo "Downloading Postman ..."
wget -q https://dl.pstmn.io/download/latest/linux?arch=64 -O postman.tar.gz
tar -xzf postman.tar.gz
rm postman.tar.gz

echo "Installing to opt..."
if [ -d "/opt/Postman" ];then
  sudo rm -rf /opt/Postman
fi
sudo mv Postman /opt/Postman

echo "Creating symbolic link..."
if [ -L "/usr/bin/postman" ];then
  sudo rm -f /usr/bin/postman
fi
sudo ln -s /opt/Postman/Postman /usr/bin/postman

echo "Installation completed successfully."

## git kraken
TEMP_DEB="$(mktemp)" \
    && LINK='https://release.gitkraken.com/linux/gitkraken-amd64.deb' \
    && wget -O "$TEMP_DEB" $LINK \
    && sudo dpkg -i "$TEMP_DEB" \
    && rm -f "$TEMP_DEB"

## dbeaver
TEMP_DEB="$(mktemp)" \
    && LINK='https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb' \
    && wget -O "$TEMP_DEB" $LINK \
    && sudo dpkg -i "$TEMP_DEB" \
    && rm -f "$TEMP_DEB"

## docker
sudo apt install apt-transport-https ca-certificates curl software-properties-common \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
    && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" \
    && sudo apt update \
    && apt-cache policy docker-ce \
    && sudo apt install docker-ce \

# pip
sudo pip install jrnl
sudo pip2 install pynvim
sudo pip3 install pynvim khal

i3

gcalcli calm --monday

gnome-session-quit
