#!/bin/bash

first_monitor=$(get-first-monitor)
second_monitor=$(get-second-monitor)
third_monitor=$(get-third-monitor)
cmd="xrandr --output $first_monitor --auto"
if [[ -n $second_monitor ]]; then
    cmd="$cmd --right-of $second_monitor"
fi

if [[ -n $third_monitor ]]; then
    cmd="$cmd --left-of $third_monitor"
fi

echo $cmd
eval $cmd
