#!/bin/bash

first_display=$(get-first-display)
second_display=$(get-second-display)
third_display=$(get-third-display)

cmd="xrandr"

if [[ -n $first_display ]]; then
    cmd="$cmd --output $first_display --auto"
fi

if [[ -n $second_display ]]; then
    cmd="$cmd --output $second_display --auto --left-of $first_display"
fi

if [[ -n $third_display ]]; then
    cmd="$cmd --output $third_display --auto --right-of $first_display"
fi

echo $cmd
eval $cmd
