#!/bin/bash
#!/usr/bin/env sh

killall -q polybar
# while pgrep -x polybar >/dev/null; do sleep 1; done

bar='simple-bar'

for i in $(xrandr --query | grep " connected" | cut -d" " -f1 | head -1);
do
    MONITOR=$i polybar $bar &
done

echo "bar launched"
