#!/bin/bash

# bind alt+shift change keyboard layout
# set default layout
# map caps to changing kyboard layout
# exec --no-startup-id setxkbmap -option grp:caps_toggle -option grp_led:caps us,ru
# exec --no-startup-id setxkbmap -option caps:escape -option 'grp:alt_shift_toggle' us,ru

setxkbmap -option caps:escape -option 'grp:alt_shift_toggle' us,ru
