#!/bin/bash

w_subject=$1
w_target=$2
w_temp="0:temp"

if i3-msg -t get_workspaces | jq ".[] | .name" | grep -q -w "$w_target"; then
  i3-msg rename workspace "$w_subject" to "$w_temp"
  i3-msg rename workspace "$w_target" to "$w_subject"
  i3-msg rename workspace "$w_temp" to "$w_target"
else
  i3-msg rename workspace "$w_subject" to "$w_target"
fi
