#!/bin/bash

I3_DIR=~/.config/i3
WORKSPACENAME=$1
LAYOUT=$2
TERMINAL=$3

visualizer="$TERMINAL -c visualizer -e cava"
lyrics="$TERMINAL -c subs -e nvim -c ':e $APPDATA_SYNC/lyrics/index.md | setl spell'"
pandora="$TERMINAL -c pianobar -e pianobar"
focus="sleep 0.25 && i3 '[class=\"pianobar\"]' focus"

$I3_DIR/init_layout "$WORKSPACENAME" "$LAYOUT" "$player" "$visualizer" "$pandora" "$lyrics" "$focus"

