#!/bin/bash

I3_DIR=~/.config/i3
WORKSPACENAME=$1
LAYOUT=$2

if i3-msg -t get_workspaces | jq ".[] | .name" | grep -q -w "$WORKSPACENAME"; then
    i3-msg "workspace $WORKSPACENAME"
else
    i3-msg "workspace $WORKSPACENAME"
    i3-msg "append_layout $I3_DIR/layouts/$LAYOUT.json"
    for i in "${@:3}"
    do
        eval $i &
    done
fi

